[package]
name = "rumblebot"
version = "0.1.0"
authors = ["Anton <antonoutkine@gmail.com>", "Noah <33094578+coolreader18@users.noreply.github.com>"]
edition = "2018"

[dependencies]
logic = { path = "../logic/logic" }
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
serde_with = "1.4.0"

tokio = { version = "0.2.21", features = ["process", "macros", "io-std"] }
futures-util = "0.3.5"
warp = "0.2.3"
static_dir = "0.1.3"
webbrowser = "0.5.4"
reqwest = { version = "0.10.6", features = ["cookies", "json"] }

runners-common = { path = "../logic/runners/common" }
wasi-runner = { path = "../logic/runners/wasi" }
wasmer-runtime = "0.17.0"
wasmer-wasi = "0.17.0"

anyhow = "1.0.31"
itertools = "0.9.0"
tempfile = "3.1.0"
structopt = "0.3.15"
shell-words = "1.0.0"
once_cell = "1.4.0"
dirs = { package = "dirs-next", version = "1.0" }
confy = "0.4.0"
async-trait = "0.1.36"
owning_ref = "0.4.1"
rpassword = "4.0.5"
strum = { version = "0.18.0", features = ["derive"] }
